# Generated by Django 5.1.4 on 2025-02-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footvogueapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount',
            new_name='discount_value',
        ),
    ]
