# Generated by Django 5.1.4 on 2025-02-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footvogueapp', '0002_rename_discount_offer_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Discount'), ('percentage', 'Percentage Discount')], default='percentage', max_length=10),
        ),
    ]
