# Generated by Django 5.1.4 on 2025-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footvogueapp', '0002_returnreason_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referraloffer',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
