# Generated by Django 5.1.4 on 2025-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footvogueapp', '0007_remove_otp_phone_number_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('email', 'otp')},
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email'], name='footvogueap_email_642268_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['otp'], name='footvogueap_otp_89542f_idx'),
        ),
    ]
