# Generated by Django 5.1.4 on 2025-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footvogueapp', '0012_remove_order_razorpay_order_id_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
