# Generated by Django 5.1.4 on 2025-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footvogueapp', '0013_returnrequest_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_status',
            field=models.CharField(choices=[('Not Cancelled', 'Not Cancelled'), ('Cancelled', 'Cancelled')], default='Not Cancelled', max_length=20),
        ),
    ]
